### ISSUE TITLE
Unable to parent teams

### ISSUE THREAD

**Issue by shousper** [pulumi/pulumi-github#214]
### What happened?

Trying to create some team hierarchy, the `parentTeamId` property expects a number. Neither the `id` nor `nodeId` of a `Team` is a number, and casting/converting them to a number doesn't work either.

### Steps to reproduce

1. Create a Team.
2. (Try to) Create another Team as a child of the first team.

### Expected Behavior

Team should be able to be assigned a parent.

### Actual Behavior

"Invalid parent team ID"

### Versions used

```
NAME                              VERSION
@pulumi/pulumi                    3.32.1
@pulumi/github                    4.11.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @shousper -

can you show us the example code you're writing so we can verify? Thank you so much!

**Comment by shousper** [comment]
Gladly @guineveresaenger

```typescript
const techTeam = new github.Team("tech", {
    description: "Technology team",
    privacy: "closed",
});

const developersTeam = new github.Team("developers", {
    parentTeamId: techTeam.id,
    description: "Tech Developers",
    privacy: "closed",
});
```

As above, trying to use `nodeId` also doesn't work. The main reason I suspect is that `parentTeamId` is expecting a number, but both `id` and `nodeId` are strings. The Terraform provider appears to just use their `id` property, but the Pulumi `id` often means something slightly different, right?

Looking at the state data, perhaps `parentTeamId` just needs to be accept a `string` so one can use `id`, or a new `teamId` property needs to be exported from `Team` resources?

Hope this helps 🙏🏻

**Comment by guineveresaenger** [comment]
@shousper that was very helpful, thank you!

You're correct in that you're running into a type mismatch here, and that was exactly the tip I needed.

Since we don't have a whole lot of control over how the terraform providers, as well as the underlying cloud APIs, implement their types, we sometimes get mismatches like this one.

Fortunately, Pulumi lets you convert Output types, as long as you're doing so in an apply() function. Most of the time, you won't need this, as luckily, input and output types match the underlying promised type.

You'll want to swap out the `parentTeamID` line for the following:

```
const developersTeam = new github.Team("developers", {
    parentTeamId: techTeam.id.apply(id => parseInt(id)), #convert the id string output to an int output
    description: "Tech Developers",
    privacy: "closed",
});
```

[Read more about Pulumi apply here.](https://leebriggs.co.uk/blog/2021/05/09/pulumi-apply)

Please feel free to reopen if this does not work for you!
