### ISSUE TITLE
Possibly breaks on nodejs `16.19.0`

### ISSUE THREAD

**Issue by santunioni** [pulumi/pulumi-github#291]
### What happened?

A simple `pulumi preview` command is stuck when running on GitHub actions. It is stuck even with no changes in the resources. Other commands such as `pulumi up` are also stuck. The bug happens intermittently, so it is difficult to reproduce.

The problem was discussed here before pinpointing it to the provider: https://github.com/pulumi/pulumi/issues/11889

### Steps to reproduce

Create a stack using
- `pulumi 3.51.1`
- s3 as stack backend
- `github plugin github v5.1.0`
- Around ~2k resources. We had ~4k resources before. I was hoping the number of resources would influence the bug, so I deleted a couple that could be deleted.
- Run a simple `pulumi preview` on GitHub actions, running on a `ubuntu-20.04`. You can apply the resources in your machine before running in a way you expect the preview to execute very fast.

Intermittently, the preview would be stuck forever.

### Expected Behavior

The `pulumi preview` should not be stuck. It should run very fast.

### Actual Behavior

The `pulumi preview` is taking forever to run. It lasted 5 hours in a workflow which we didn't configure timeout.

### Output of `pulumi about`

```
CLI          
Version      3.51.1
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME    VERSION
github  5.1.0
nodejs  unknown

Host     
OS       darwin
Version  12.6
Arch     arm64

This project is written in nodejs: executable='/Users/vinicius.vargas/.nvm/versions/node/v16.17.1/bin/node' version='v16.17.1'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
@santunioni when you say "Intermittently, the preview would be stuck forever", how often is intermittently? Does it get stuck 1/2 times, 1/10, 1/100?

**Comment by santunioni** [comment]
@iwahbe, I didn't measure it precisely with a large sample, but my guess is that we get only ~10% success or less.

**Comment by santunioni** [comment]
I am testing v5.2.0 with nodejs 16.19.0 and it also stucked

**Comment by AaronFriel** [comment]
Hey @santunioni, I think you may be running into an issue a known issue with the open source backends.

To ensure that no data is lost, the checkpoint file (state of all resources) is updated each time a resource's state is modified during a Pulumi deployment, and the size of that checkpoint is proportional to the all of the resources in the stack. In other words, the bandwidth scales with O(n<sup>2</sup>). Doubling the resources will quadruple uploads.

There are a few options you could try:

First, run Pulumi deployments from a data center in the US, such as in AWS or GitHub Actions. That should have a much faster connection.

Second, if you would like to try out the Pulumi Service instead of using S3, it would use an optimized behavior to send smaller uploads. The service is better able to handle incremental updates because it works against a database and not a "simple storage service" (aka S3). If this is interesting to you, we have docs on [migrating between backends](https://www.pulumi.com/docs/intro/concepts/state/#migrating-between-state-backends) to help try this out. 

Third, though one I recommend only if absolutely necessary, is setting an environment variable which causes Pulumi to skip sending checkpoints during deployments, waiting until the end:

```
PULUMI_EXPERIMENTAL=true
PULUMI_SKIP_CHECKPOINTS=true
```

Note that this will opt Pulumi into other experimental behavior.

**Comment by santunioni** [comment]
@AaronFriel, what happens if I skip checkpoints and my `pulumi up` fails in a given resource? Will pulumi update the checkpoint file anyway or will I lose the progress that `pulumi up` made on other resources?

**Comment by AaronFriel** [comment]
It depends on the manner in which Pulumi fails when the env var is set to skip checkpoints. 

If the resource fails "normally", in a way that the provider catches the failure and reports the error, the checkpoint will be updated.

If the Pulumi engine panics and exits prematurely, any progress during the update would be lost.

**Comment by AaronFriel** [comment]
@santunioni were you able to verify if either suggestion helped with the apparent hang?

**Comment by aq17** [comment]
Going to close this as stale, since the provider version at the time is now a few releases out of date. Please reopen the issue if you're still having trouble.
