### ISSUE TITLE
Make `description` param of `EnterpriseOrganization` optional to avoid permission errors

### ISSUE THREAD

**Issue by kirgene** [pulumi/pulumi-github#412]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We use two github users: `ent_user` and `org_user` for provisioning github org:
* `ent_user` is used only for creating enterprise organization
* `org_user` is used for creating repos and other resources inside the org.

The following code fails.

```python
github_organization = github.EnterpriseOrganization(
    "organization",
    name=org_name,
    enterprise_id=enterprise_id,
    # description="Example Organization",
    billing_email="test@example.com",
    admin_logins=[org_user],
    opts=pulumi.ResourceOptions(provider=ent_provider)
)
```
Tracing the HTTP calls of the following code shows it first creates an organization with GraphQL API and then issues a PATCH REST API that only sets the org description ( `{ "description": "" }` ). And the PATCH request fails with a permission error.
That's because `admin_logins` contain only `org_user` and the PATCH request uses the `ent_user` PAT.

### Solution

It's better to make the `description` param optional to avoid issuing the extra PATCH call during org creation, especially if there is already an `OrganizationSettings` resource that can be used to set the description for the org.

**Comment by rquitales** [comment]
Hello @kirgene,

We apologize for the issue you're facing. I've investigated the upstream provider, and it seems that they already handle the scenario where the V3 API isn't accessed if the `description` field is empty. You can find a reference to this in the provider's code here: [resource_github_enterprise_organization.go Lines 91-116](https://github.com/integrations/terraform-provider-github/blame/470c1c43a4bffc7f5e288ac87ad80c7325d9032f/github/resource_github_enterprise_organization.go#L91-L116).

In order to assist you further, could you please provide the output of the `pulumi about` command from within the Pulumi project's folder? This information will help us understand the environment and versions of dependencies you're using within your Pulumi program. With this information, we can work towards resolving the issue more effectively.

Thank you for your cooperation and patience.

**Comment by kirgene** [comment]
Hello @rquitales 

Here are the Pulumi env details:

```
CLI          
Version      3.77.1
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.42.0
github  5.15.0
python  unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

Dependencies:
NAME           VERSION
pip            23.2.1
pulumi-aws     5.42.0
pulumi-github  5.15.0
setuptools     68.0.0
wheel          0.41.1
```

**Comment by kirgene** [comment]
@rquitales I've updated `pulumi-github` to `5.16.0` and it looks like the original issue is gone.

But we have another problem now: removing `EnterpriseOrganization` uses `ent_user` PAT, which doesn't have the required permission. Could we use a different github provider during deletion: `org_user` PAT that is an owner of the org

**Comment by mikhailshilkov** [comment]
It sounds like the original problem is fixed. We haven't received a repro for the new problem, so I'll go ahead and close this issue. If you still experience a problem, please open a new issue with a repro. Thank you!
